/**
 * CampusConnect v2.0 — Mock Data
 * Realistic dummy data for development. Replace with DB calls in production.
 */

import type { GigCardData } from "@/components/ui/GigCard"

export const mockGigs: GigCardData[] = [
  {
    id: "g1",
    title: "React Frontend Developer for Dashboard MVP",
    company: "Acme AI Studio",
    skills: ["React", "TypeScript", "Tailwind CSS"],
    budget: 2400,
    duration: "3 weeks",
    postedAt: new Date(Date.now() - 3_600_000 * 2),
    matchPercent: 94,

    remote: true,
  },
  {
    id: "g2",
    title: "Python Data Pipeline — Fintech Startup",
    company: "CreditFlow",
    skills: ["Python", "Pandas", "PostgreSQL"],
    budget: 3500,
    duration: "2 weeks",
    postedAt: new Date(Date.now() - 3_600_000 * 5),
    matchPercent: 87,

    remote: true,
  },
  {
    id: "g3",
    title: "UI/UX Design for Mobile App (Figma)",
    company: "StartupX",
    skills: ["Figma", "Design"],
    budget: 2200,
    duration: "10 days",
    postedAt: new Date(Date.now() - 3_600_000 * 12),
    matchPercent: 76,

    remote: false,
  },
  {
    id: "g4",
    title: "Content Writer — SaaS Product Blog",
    company: "GrowthHQ",
    skills: ["Marketing", "Content Writing", "SEO"],
    budget: 1200,
    duration: "1 week",
    postedAt: new Date(Date.now() - 3_600_000 * 20),
    matchPercent: 65,

    remote: true,
  },
  {
    id: "g5",
    title: "Full-Stack Next.js Developer",
    company: "QuickHire",
    skills: ["Next.js", "React", "Prisma", "PostgreSQL"],
    budget: 5000,
    duration: "1 month",
    postedAt: new Date(Date.now() - 86_400_000),
    matchPercent: 91,

    remote: true,
  },
  {
    id: "g6",
    title: "Social Media & Growth Hacking",
    company: "BrandFlow",
    skills: ["Marketing", "Instagram", "Analytics"],
    budget: 1500,
    duration: "2 weeks",
    postedAt: new Date(Date.now() - 86_400_000 * 2),
    matchPercent: 58,

    remote: false,
  },
]

export const mockInternships = [
  {
    id: "i1",
    title: "Frontend Engineering Intern",
    company: "Razorpay",
    stage: "Series C",
    stipend: 8000,
    duration: "3 months",
    remote: true,
    skills: ["React", "TypeScript", "GraphQL"],
    matchPercent: 94,
    postedAt: new Date(Date.now() - 3_600_000 * 4),
    deadline: new Date(Date.now() + 86_400_000 * 3),
    exclusive: true,
  },
  {
    id: "i2",
    title: "Backend Developer Intern",
    company: "CRED",
    stage: "Series D",
    stipend: 12000,
    duration: "6 months",
    remote: false,
    skills: ["Python", "Django", "Redis", "Kafka"],
    matchPercent: 82,
    postedAt: new Date(Date.now() - 3_600_000 * 8),
    deadline: new Date(Date.now() + 86_400_000 * 10),
    exclusive: true,
  },
  {
    id: "i3",
    title: "Product Design Intern",
    company: "Groww",
    stage: "Series E",
    stipend: 6000,
    duration: "2 months",
    remote: true,
    skills: ["Figma", "Design", "User Research"],
    matchPercent: 71,
    postedAt: new Date(Date.now() - 86_400_000),
    deadline: new Date(Date.now() + 86_400_000 * 7),
    exclusive: false,
  },
  {
    id: "i4",
    title: "Data Science Intern",
    company: "PhonePe",
    stage: "Series F",
    stipend: 15000,
    duration: "4 months",
    remote: false,
    skills: ["Python", "ML", "NumPy", "SQL"],
    matchPercent: 89,
    postedAt: new Date(Date.now() - 3_600_000 * 6),
    deadline: new Date(Date.now() + 86_400_000 * 5),
    exclusive: false,
  },
  {
    id: "i5",
    title: "Mobile App Developer Intern",
    company: "Zepto",
    stage: "Series C",
    stipend: 10000,
    duration: "3 months",
    remote: true,
    skills: ["React Native", "TypeScript", "Firebase"],
    matchPercent: 76,
    postedAt: new Date(Date.now() - 86_400_000 * 2),
    deadline: new Date(Date.now() + 86_400_000 * 14),
    exclusive: false,
  },
  {
    id: "i6",
    title: "DevOps / Cloud Intern",
    company: "BrowserStack",
    stage: "Series B",
    stipend: 12000,
    duration: "6 months",
    remote: true,
    skills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    matchPercent: 63,
    postedAt: new Date(Date.now() - 86_400_000 * 3),
    deadline: new Date(Date.now() + 86_400_000 * 20),
    exclusive: false,
  },
]

export const mockStudents = [
  {
    id: "s1",
    name: "Arjun Sharma",
    username: "arjun",
    college: "NIT Trichy",
    branch: "CSE, 3rd Year",
    skills: ["React", "TypeScript", "Node.js"],
    gigsCompleted: 4,
    totalEarned: 8400,
    avgRating: 4.9,
    available: true,
    matchPercent: 94,
  },
  {
    id: "s2",
    name: "Priya Nair",
    username: "priya",
    college: "BITS Pilani Goa",
    branch: "CS, 4th Year",
    skills: ["Python", "ML", "Data Science"],
    gigsCompleted: 7,
    totalEarned: 15600,
    avgRating: 5.0,
    available: true,
    matchPercent: 88,
  },
  {
    id: "s3",
    name: "Rohan Kumar",
    username: "rohan",
    college: "VIT Vellore",
    branch: "ECE, 2nd Year",
    skills: ["Figma", "Design", "Branding"],
    gigsCompleted: 3,
    totalEarned: 5400,
    avgRating: 4.7,
    available: false,
    matchPercent: 76,
  },
]

export const mockNotifications = [
  {
    id: "n1",
    type: "payment" as const,
    title: "Payment Released 🎉",
    description: "₹2,400 from Acme AI Studio released to your account.",
    time: "2 minutes ago",
    read: false,
  },
  {
    id: "n2",
    type: "match" as const,
    title: "New 94% Match Found",
    description: "Razorpay internship — ₹8,000/mo · AI recommends you apply now.",
    time: "18 minutes ago",
    read: false,
  },
  {
    id: "n3",
    type: "gig" as const,
    title: "Application Accepted ✅",
    description: "Your application for React Dashboard gig has been accepted. Escrow locked.",
    time: "1 hour ago",
    read: false,
  },
]

export const mockRoadmaps = [
  {
    id: "r1",
    goal: "SDE at Flipkart",
    weeks: [
      { week: 1, task: "Arrays & Hashing in Python", done: true, hours: 10 },
      { week: 2, task: "System Design Basics", done: false, active: true, hours: 12 },
      { week: 3, task: "Trees & Graphs (DSA)", done: false, hours: 14 },
      { week: 4, task: "Build: E-commerce Backend MVP", done: false, hours: 16 },
      { week: 5, task: "Mock Interviews (LeetCode 50)", done: false, hours: 10 },
      { week: 6, task: "Final Project + Portfolio Polish", done: false, hours: 8 },
    ],
  },
]
